-- MySQL Script generated by MySQL Workbench
-- Wed Jun 19 20:26:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_mpb_spring
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_mpb_spring` ;

-- -----------------------------------------------------
-- Schema bd_mpb_spring
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_mpb_spring` DEFAULT CHARACTER SET utf8 ;
USE `bd_mpb_spring` ;

-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`distrito` (
  `id_distrito` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_distrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`apoderado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`apoderado` (
  `dni` CHAR(8) NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `celular` CHAR(9) NULL,
  `correo` VARCHAR(50) NULL,
  `pass` VARCHAR(32) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`estudiante` (
  `dni` CHAR(8) NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `dni_apoderado` CHAR(8) NOT NULL,
  `celular` CHAR(9) NULL,
  `correo` VARCHAR(50) NULL,
  `id_distrito` INT NOT NULL,
  `direccion` VARCHAR(50) NULL,
  `pass` VARCHAR(32) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC) VISIBLE,
  INDEX `fk_estudiante_distrito_idx` (`id_distrito` ASC) VISIBLE,
  INDEX `fk_estudiante_apoderado1_idx` (`dni_apoderado` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_distrito`
    FOREIGN KEY (`id_distrito`)
    REFERENCES `bd_mpb_spring`.`distrito` (`id_distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_apoderado1`
    FOREIGN KEY (`dni_apoderado`)
    REFERENCES `bd_mpb_spring`.`apoderado` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`nota` (
  `id_nota` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `nota_1` TINYINT NULL,
  `nota_2` TINYINT NULL,
  `nota_3` TINYINT NULL,
  `promedio` TINYINT NULL,
  `fecha` DATE NULL,
  `dni_estudiante` CHAR(8) NOT NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `fk_nota_curso1_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_nota_estudiante1_idx` (`dni_estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_nota_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bd_mpb_spring`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_estudiante1`
    FOREIGN KEY (`dni_estudiante`)
    REFERENCES `bd_mpb_spring`.`estudiante` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`trabajador` (
  `id_trabajador` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dni` CHAR(8) NULL,
  `fecha_nacimiento` DATE NULL,
  `celular` CHAR(9) NULL,
  `id_distrito` INT NOT NULL,
  `direccion` VARCHAR(50) NULL,
  `correo` VARCHAR(50) NULL,
  `pass` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_trabajador`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  INDEX `fk_trabajador_distrito1_idx` (`id_distrito` ASC) VISIBLE,
  CONSTRAINT `fk_trabajador_distrito1`
    FOREIGN KEY (`id_distrito`)
    REFERENCES `bd_mpb_spring`.`distrito` (`id_distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`nivel` (
  `id_nivel` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_nivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`grado` (
  `id_grado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_nivel` INT NOT NULL,
  PRIMARY KEY (`id_grado`),
  INDEX `fk_grado_nivel1_idx` (`id_nivel` ASC) VISIBLE,
  CONSTRAINT `fk_grado_nivel1`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `bd_mpb_spring`.`nivel` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`seccion` (
  `id_seccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` CHAR(1) NULL,
  `n_estudiantes` TINYINT NULL,
  `id_grado` INT NOT NULL,
  PRIMARY KEY (`id_seccion`),
  INDEX `fk_seccion_grado1_idx` (`id_grado` ASC) VISIBLE,
  CONSTRAINT `fk_seccion_grado1`
    FOREIGN KEY (`id_grado`)
    REFERENCES `bd_mpb_spring`.`grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`matricula` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `nivel` INT NULL,
  `grado` INT NULL,
  `dni_estudiante` CHAR(8) NOT NULL,
  `id_seccion` INT NOT NULL,
  `id_trabajador` INT NOT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `fk_matricula_estudiante1_idx` (`dni_estudiante` ASC) VISIBLE,
  INDEX `fk_matricula_seccion1_idx` (`id_seccion` ASC) VISIBLE,
  INDEX `fk_matricula_trabajador1_idx` (`id_trabajador` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_estudiante1`
    FOREIGN KEY (`dni_estudiante`)
    REFERENCES `bd_mpb_spring`.`estudiante` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_seccion1`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `bd_mpb_spring`.`seccion` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_trabajador1`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `bd_mpb_spring`.`trabajador` (`id_trabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`horario_cabecera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`horario_cabecera` (
  `id_horario_cabecera` INT NOT NULL AUTO_INCREMENT,
  `id_trabajador` INT NOT NULL,
  `estado` TINYINT NULL,
  `id_seccion` INT NOT NULL,
  PRIMARY KEY (`id_horario_cabecera`),
  INDEX `fk_horario_trabajador1_idx` (`id_trabajador` ASC) VISIBLE,
  INDEX `fk_horario_cabecera_seccion1_idx` (`id_seccion` ASC) VISIBLE,
  CONSTRAINT `fk_horario_trabajador1`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `bd_mpb_spring`.`trabajador` (`id_trabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_cabecera_seccion1`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `bd_mpb_spring`.`seccion` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`horario_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`horario_detalle` (
  `id_horario_detalle` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `dia` VARCHAR(45) NULL,
  `hora_inicio` TIME NULL,
  `hora_fin` TIME NULL,
  `id_curso` INT NOT NULL,
  `id_horario_cabecera` INT NOT NULL,
  PRIMARY KEY (`id_horario_detalle`),
  INDEX `fk_horario_detalle_horario_cabecera1_idx` (`id_horario_cabecera` ASC) VISIBLE,
  INDEX `fk_horario_detalle_curso1_idx` (`id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_horario_detalle_horario_cabecera1`
    FOREIGN KEY (`id_horario_cabecera`)
    REFERENCES `bd_mpb_spring`.`horario_cabecera` (`id_horario_cabecera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_detalle_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bd_mpb_spring`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`asistencia` (
  `id_asistencia` INT NOT NULL AUTO_INCREMENT,
  `dni_estudiante` CHAR(8) NOT NULL,
  `hora_asistencia` TIME NULL,
  `estado` TINYINT NULL,
  `id_horario_detalle` INT NOT NULL,
  INDEX `fk_asistencia_estudiante1_idx` (`dni_estudiante` ASC) VISIBLE,
  PRIMARY KEY (`id_asistencia`),
  INDEX `fk_asistencia_horario_detalle1_idx` (`id_horario_detalle` ASC) VISIBLE,
  CONSTRAINT `fk_asistencia_estudiante1`
    FOREIGN KEY (`dni_estudiante`)
    REFERENCES `bd_mpb_spring`.`estudiante` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asistencia_horario_detalle1`
    FOREIGN KEY (`id_horario_detalle`)
    REFERENCES `bd_mpb_spring`.`horario_detalle` (`id_horario_detalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`malla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`malla` (
  `id_malla` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_grado` INT NOT NULL,
  PRIMARY KEY (`id_malla`),
  INDEX `fk_malla_curso1_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_malla_grado1_idx` (`id_grado` ASC) VISIBLE,
  CONSTRAINT `fk_malla_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bd_mpb_spring`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_malla_grado1`
    FOREIGN KEY (`id_grado`)
    REFERENCES `bd_mpb_spring`.`grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`justificion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`justificion` (
  `id_justificion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `fecha` DATE NULL,
  `dni_estudiante` CHAR(8) NOT NULL,
  PRIMARY KEY (`id_justificion`),
  INDEX `fk_justificion_estudiante1_idx` (`dni_estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_justificion_estudiante1`
    FOREIGN KEY (`dni_estudiante`)
    REFERENCES `bd_mpb_spring`.`estudiante` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`citaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`citaciones` (
  `id_citaciones` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `fecha` DATETIME NULL,
  `estado` CHAR(1) NULL,
  `dni_estudiante` CHAR(8) NOT NULL,
  PRIMARY KEY (`id_citaciones`),
  INDEX `fk_citaciones_estudiante1_idx` (`dni_estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_citaciones_estudiante1`
    FOREIGN KEY (`dni_estudiante`)
    REFERENCES `bd_mpb_spring`.`estudiante` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`permisos` (
  `id_permisos` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `estado` CHAR(1) NULL,
  `dni_estudiante` CHAR(8) NOT NULL,
  PRIMARY KEY (`id_permisos`),
  INDEX `fk_permisos_estudiante1_idx` (`dni_estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_permisos_estudiante1`
    FOREIGN KEY (`dni_estudiante`)
    REFERENCES `bd_mpb_spring`.`estudiante` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`trabajador_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`trabajador_curso` (
  `id_trabajador` INT NOT NULL,
  `id_curso` INT NOT NULL,
  INDEX `fk_trabajador_has_curso_curso1_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_trabajador_has_curso_trabajador1_idx` (`id_trabajador` ASC) VISIBLE,
  CONSTRAINT `fk_trabajador_has_curso_trabajador1`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `bd_mpb_spring`.`trabajador` (`id_trabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajador_has_curso_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bd_mpb_spring`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb_spring`.`comunicado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb_spring`.`comunicado` (
  `id_comunicado` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(500) NULL,
  `fecha` DATETIME NULL,
  `dni_estudiante` CHAR(8) NOT NULL,
  PRIMARY KEY (`id_comunicado`),
  INDEX `fk_comunicado_estudiante1_idx` (`dni_estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_comunicado_estudiante1`
    FOREIGN KEY (`dni_estudiante`)
    REFERENCES `bd_mpb_spring`.`estudiante` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
