-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 00:01:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_mpb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_mpb` ;

-- -----------------------------------------------------
-- Schema bd_mpb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_mpb` DEFAULT CHARACTER SET utf8 ;
USE `bd_mpb` ;

-- -----------------------------------------------------
-- Table `bd_mpb`.`distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`distrito` (
  `id_distrito` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_distrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`apoderado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`apoderado` (
  `id_apoderado` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dni` CHAR(8) NULL,
  `celular` CHAR(9) NULL,
  `correo` VARCHAR(50) NULL,
  `pass` VARCHAR(32) NULL,
  PRIMARY KEY (`id_apoderado`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`estudiante` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dni` CHAR(8) NULL,
  `fecha_nacimiento` DATE NULL,
  `id_apoderado` INT NOT NULL,
  `celular` CHAR(9) NULL,
  `correo` VARCHAR(50) NULL,
  `id_distrito` INT NOT NULL,
  `direccion` VARCHAR(50) NULL,
  `pass` VARCHAR(32) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_estudiante`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC) VISIBLE,
  INDEX `fk_estudiante_distrito_idx` (`id_distrito` ASC) VISIBLE,
  INDEX `fk_estudiante_apoderado1_idx` (`id_apoderado` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_distrito`
    FOREIGN KEY (`id_distrito`)
    REFERENCES `bd_mpb`.`distrito` (`id_distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_apoderado1`
    FOREIGN KEY (`id_apoderado`)
    REFERENCES `bd_mpb`.`apoderado` (`id_apoderado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(2700) NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`nota` (
  `id_nota` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `nota_1` TINYINT NULL,
  `nota_2` TINYINT NULL,
  `nota_3` TINYINT NULL,
  `promedio` TINYINT NULL,
  `id_estudiante` INT NOT NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `fk_nota_curso1_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_nota_estudiante1_idx` (`id_estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_nota_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bd_mpb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `bd_mpb`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`trabajador` (
  `id_trabajador` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dni` CHAR(8) NULL,
  `fecha_nacimiento` DATE NULL,
  `celular` CHAR(9) NULL,
  `correo` VARCHAR(50) NULL,
  `pass` VARCHAR(45) NULL,
  `id_distrito` INT NOT NULL,
  PRIMARY KEY (`id_trabajador`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  INDEX `fk_trabajador_distrito1_idx` (`id_distrito` ASC) VISIBLE,
  CONSTRAINT `fk_trabajador_distrito1`
    FOREIGN KEY (`id_distrito`)
    REFERENCES `bd_mpb`.`distrito` (`id_distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`nivel` (
  `id_nivel` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_nivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`grado` (
  `id_grado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_nivel` INT NOT NULL,
  PRIMARY KEY (`id_grado`),
  INDEX `fk_grado_nivel1_idx` (`id_nivel` ASC) VISIBLE,
  CONSTRAINT `fk_grado_nivel1`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `bd_mpb`.`nivel` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`seccion` (
  `id_seccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` CHAR(1) NULL,
  `n_estudiantes` TINYINT NULL,
  `id_grado` INT NOT NULL,
  PRIMARY KEY (`id_seccion`),
  INDEX `fk_seccion_grado1_idx` (`id_grado` ASC) VISIBLE,
  CONSTRAINT `fk_seccion_grado1`
    FOREIGN KEY (`id_grado`)
    REFERENCES `bd_mpb`.`grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`matricula` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `nivel` INT NULL,
  `grado` INT NULL,
  `id_estudiante` INT NOT NULL,
  `id_seccion` INT NOT NULL,
  `id_trabajador` INT NOT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `fk_matricula_estudiante1_idx` (`id_estudiante` ASC) VISIBLE,
  UNIQUE INDEX `id_estudiante_UNIQUE` (`id_estudiante` ASC) VISIBLE,
  INDEX `fk_matricula_seccion1_idx` (`id_seccion` ASC) VISIBLE,
  INDEX `fk_matricula_trabajador1_idx` (`id_trabajador` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `bd_mpb`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_seccion1`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `bd_mpb`.`seccion` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_trabajador1`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `bd_mpb`.`trabajador` (`id_trabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`horario` (
  `id_horario` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(45) NULL,
  `hora_inicio` TIME NULL,
  `hora_fin` TIME NULL,
  `aula` TINYINT NULL,
  `id_curso` INT NOT NULL,
  `id_trabajador` INT NOT NULL,
  PRIMARY KEY (`id_horario`),
  INDEX `fk_horario_curso1_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_horario_trabajador1_idx` (`id_trabajador` ASC) VISIBLE,
  CONSTRAINT `fk_horario_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bd_mpb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_trabajador1`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `bd_mpb`.`trabajador` (`id_trabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`asistencia` (
  `id_asistencia` INT NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT NOT NULL,
  `id_horario` INT NOT NULL,
  `estado` TINYINT NULL,
  INDEX `fk_asistencia_estudiante1_idx` (`id_estudiante` ASC) VISIBLE,
  INDEX `fk_asistencia_horario1_idx` (`id_horario` ASC) VISIBLE,
  PRIMARY KEY (`id_asistencia`),
  CONSTRAINT `fk_asistencia_estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `bd_mpb`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asistencia_horario1`
    FOREIGN KEY (`id_horario`)
    REFERENCES `bd_mpb`.`horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`malla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`malla` (
  `id_malla` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_grado` INT NOT NULL,
  PRIMARY KEY (`id_malla`),
  INDEX `fk_malla_curso1_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_malla_grado1_idx` (`id_grado` ASC) VISIBLE,
  CONSTRAINT `fk_malla_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bd_mpb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_malla_grado1`
    FOREIGN KEY (`id_grado`)
    REFERENCES `bd_mpb`.`grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_mpb`.`justificion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`justificion` (
  `id_justificion` INT NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(255) NULL,
  `justificacion` VARCHAR(255) NULL,
  `id_apoderado` INT NOT NULL,
  PRIMARY KEY (`id_justificion`),
  INDEX `fk_justificion_apoderado1_idx` (`id_apoderado` ASC) VISIBLE,
  CONSTRAINT `fk_justificion_apoderado1`
    FOREIGN KEY (`id_apoderado`)
    REFERENCES `bd_mpb`.`apoderado` (`id_apoderado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `bd_mpb`.`citaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`citaciones` (
  `id_citaciones` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `fecha` DATETIME NULL,
  `estado` TINYINT NULL,
  `id_apoderado` INT NOT NULL,
  PRIMARY KEY (`id_citaciones`),
  INDEX `fk_citaciones_apoderado1_idx` (`id_apoderado` ASC) VISIBLE,
  CONSTRAINT `fk_citaciones_apoderado1`
    FOREIGN KEY (`id_apoderado`)
    REFERENCES `bd_mpb`.`apoderado` (`id_apoderado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `bd_mpb`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_mpb`.`permisos` (
  `id_permisos` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `estado` TINYINT NULL,
  `id_apoderado` INT NOT NULL,
  PRIMARY KEY (`id_permisos`),
  INDEX `fk_permisos_apoderado1_idx` (`id_apoderado` ASC) VISIBLE,
  CONSTRAINT `fk_permisos_apoderado1`
    FOREIGN KEY (`id_apoderado`)
    REFERENCES `bd_mpb`.`apoderado` (`id_apoderado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
