use bd_mpb;

-- distrito ()
insert into distrito (nombre) values ('LIMA');
insert into distrito (nombre) values ('ANCÓN');
insert into distrito (nombre) values ('ATE');
insert into distrito (nombre) values ('BARRANCO');
insert into distrito (nombre) values ('BREÑA');
insert into distrito (nombre) values ('CARABAYLLO');
insert into distrito (nombre) values ('CHACLACAYO');
insert into distrito (nombre) values ('CHORRILLOS');
insert into distrito (nombre) values ('CIENEGUILLA');
insert into distrito (nombre) values ('COMAS');
insert into distrito (nombre) values ('EL AGUSTINO');
insert into distrito (nombre) values ('INDEPENDENCIA');
insert into distrito (nombre) values ('JESÚS MARÍA');
insert into distrito (nombre) values ('LA MOLINA');
insert into distrito (nombre) values ('LA VICTORIA');
insert into distrito (nombre) values ('LINCE');
insert into distrito (nombre) values ('LOS OLIVOS');
insert into distrito (nombre) values ('LURIGANCHO');
insert into distrito (nombre) values ('LURÍN');
insert into distrito (nombre) values ('MAGDALENA DEL MAR');
insert into distrito (nombre) values ('PUEBLO LIBRE');
insert into distrito (nombre) values ('MIRAFLORES');
insert into distrito (nombre) values ('PACHACAMAC');
insert into distrito (nombre) values ('PUCUSANA');
insert into distrito (nombre) values ('PUENTE PIEDRA');
insert into distrito (nombre) values ('PUNTA HERMOSA');
insert into distrito (nombre) values ('PUNTA NEGRA');
insert into distrito (nombre) values ('RÍMAC');
insert into distrito (nombre) values ('SAN BARTOLO');
insert into distrito (nombre) values ('SAN BORJA');
insert into distrito (nombre) values ('SAN ISIDRO');
insert into distrito (nombre) values ('SAN JUAN DE LURIGANCHO');
insert into distrito (nombre) values ('SAN JUAN DE MIRAFLORES');
insert into distrito (nombre) values ('SAN LUIS');
insert into distrito (nombre) values ('SAN MARTÍN DE PORRES');
insert into distrito (nombre) values ('SAN MIGUEL');
insert into distrito (nombre) values ('SANTA ANITA');
insert into distrito (nombre) values ('SANTA MARÍA DEL MAR');
insert into distrito (nombre) values ('SANTA ROSA');
insert into distrito (nombre) values ('SANTIAGO DE SURCO');
insert into distrito (nombre) values ('SURQUILLO');
insert into distrito (nombre) values ('VILLA EL SALVADOR');
insert into distrito (nombre) values ('VILLA MARÍA DEL TRIUNFO');

-- estudiante (10)
insert into estudiante (id_estudiante, nombres, apellidos, dni, fecha_nacimiento, id_apoderado, celular, correo, id_distrito, direccion, pass) values (1, 'Ruthy', 'Tapsell', 92615032, '2013-01-12', 10, 993380542, 'rtapsell0@vistaprint.com', 18, '517 Cottonwood Drive', 123);
insert into estudiante (id_estudiante, nombres, apellidos, dni, fecha_nacimiento, id_apoderado, celular, correo, id_distrito, direccion, pass) values (2, 'Martha', 'Cuttings', 92017015, '2017-09-10', 15, 980610301, 'mcuttings1@mysql.com', 20, '9 Stone Corner Place', 123);
insert into estudiante (id_estudiante, nombres, apellidos, dni, fecha_nacimiento, id_apoderado, celular, correo, id_distrito, direccion, pass) values (3, 'Elsworth', 'Dimitrescu', 84708047, '2017-08-19', 6, 909127792, 'edimitrescu2@vkontakte.ru', 25, '7 Shopko Avenue', 123);
insert into estudiante (id_estudiante, nombres, apellidos, dni, fecha_nacimiento, id_apoderado, celular, correo, id_distrito, direccion, pass) values (4, 'Rodina', 'Lunnon', 96497892, '2016-05-16', 43, 984082253, 'rlunnon3@etsy.com', 12, '12 Bonner Trail', 123);
insert into estudiante (id_estudiante, nombres, apellidos, dni, fecha_nacimiento, id_apoderado, celular, correo, id_distrito, direccion, pass) values (5, 'Katusha', 'Yurinov', 91326920, '2012-05-15', 43, 977405151, 'kyurinov4@nhs.uk', 19, '4 Nevada Trail', 123);
insert into estudiante (id_estudiante, nombres, apellidos, dni, fecha_nacimiento, id_apoderado, celular, correo, id_distrito, direccion, pass) values (6, 'Nert', 'Tuppeny', 91510741, '2017-03-01', 26, 996857560, 'ntuppeny5@reddit.com', 17, '3 Surrey Terrace', 123);
insert into estudiante (id_estudiante, nombres, apellidos, dni, fecha_nacimiento, id_apoderado, celular, correo, id_distrito, direccion, pass) values (7, 'Duffie', 'Sagg', 87364414, '2014-11-14', 13, 957510148, 'dsagg6@bloglovin.com', 23, '8724 Havey Plaza', 123);
insert into estudiante (id_estudiante, nombres, apellidos, dni, fecha_nacimiento, id_apoderado, celular, correo, id_distrito, direccion, pass) values (8, 'Audi', 'Fabry', 93061201, '2014-05-20', 6, 993000918, 'afabry7@histats.com', 7, '2252 High Crossing Park', 123);
insert into estudiante (id_estudiante, nombres, apellidos, dni, fecha_nacimiento, id_apoderado, celular, correo, id_distrito, direccion, pass) values (9, 'Randal', 'Hickinbottom', 96992018, '2013-06-17', 17, 919232380, 'rhickinbottom8@goo.ne.jp', 13, '29 Jenna Court', 123);
insert into estudiante (id_estudiante, nombres, apellidos, dni, fecha_nacimiento, id_apoderado, celular, correo, id_distrito, direccion, pass) values (10, 'Giuditta', 'Attow', 81422902, '2013-02-08', 21, 900569514, 'gattow9@imgur.com', 40, '098 Pearson Center', 123);